#' Find revised items and store them into an info list
#'
#' Given 1) examdeveloper item output in xlsx format and 2) an item file with benchmark difficulties,
#' find the items that have been revised and optionally write an initial anchor file
#'
#' @param bench_csv Path to ITEMS_Total.csv winsteps output from an analysis considered benchmark. Use of {fs} package encouraged for generating paths.
#' @param ed_xlsx Path to ExamDeveloper Excel file with current item stats. Use of {fs} package encouraged for generating paths.
#' @param pooled Logical. This parameter may be used to place data, but it could be removed if info_list contains this information.
#' @param write_anc Logical. FALSE only stores the initial anchors, TRUE writes them
#' @param info_list name of the info_list generated by info_exam()
#'
#' @return info_list is returned, not assigned. As an optional side effect, the initial anchor file can be written.
#' @export
#'
#' @examples
#' info_list <- init_anchors(bench_csv = fs::path_wd("data/ITEMS_Total.csv"),
#'                           ed_xlsx = fs::path_wd("data/ED.xlsx"),
#'                           write_anc = FALSE, info_list = info_list)
init_anchors <- function(bench_csv = bench_csv, ed_xlsx = ed_xlsx, pooled = FALSE, write_anc = FALSE, info_list = info_list){
info_list = info_list
bdiffs <- read.csv(bench_csv, skip=1, header=TRUE) %>%
  dplyr::filter(STATUS!=-3)
ed_stats <- ed_xlsx %>% openxlsx::read.xlsx(sheet=1,colNames=TRUE) %>%
                dplyr::mutate(NAME = as.numeric(Question.ID))


revised_set <- ed_stats %>% dplyr::left_join(bdiffs,by="NAME") %>%
  dplyr::filter(!is.na(MEASURE) & is.na(`Analysis.set.name.(Default)`))


revised_items <- pull(revised_set, NAME)

#drop revised items from anchor set
bdiffs <- bdiffs[ ! bdiffs$NAME %in% revised_items, ]

#only need item IDs and measures
bdiffs <- bdiffs[c("NAME","MEASURE")]

#current items
#++ NOTE form can be read in from Hobbes Original, to standardize?
#++  ex: form <- read.table(fs::path_wd("Hobbes Original/ITEMS_Total.csv"),skip=1,header=TRUE,sep = ",")
form <- read.table(path_home_r('Doing/local_scoring/AOBFPEEIC/Hobbes Original/ITEMS_Total.csv'),
                   skip=1,header=TRUE,sep = ",") %>%
  dplyr::select(NAME, ENTRY)
#only need IDs & entry number of current items

#merge bench diffs to current items; filter by those items with bdiffs
anchors <- dplyr::left_join(form, bdiffs, by = "NAME") %>%
  dplyr::filter(!is.na(MEASURE))

#store the Winsteps anchor file to be written
info_list[["init_anchors_df"]] <- anchors[c("ENTRY","MEASURE")]
if(write_anc == TRUE){
write.table(anchors[c("ENTRY","MEASURE")],
            file = glue::glue("{path1}/Anchor_{exam_code}.anc"),
            sep = " ",
            row.names = FALSE,
            col.names = FALSE,
            quote = FALSE)
  message("Anchors Written.")

}else{
  message("No Anchors Written.")
}
  return(info_list)
}
